purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.4641577
  brandStrength: 0
  lightness: 0.5250896
  brandColors:
    - '#FFFFFF'
    - '#4576BE'
    - '#333333'
    - '#CC181E'
    - '#ABBDD9'
  rhythmicContrast: 0.5501792
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
cta:
  bucket: null
  version: null
  domain: null
name: Jameslawson
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.3100359
layout_spectrum: 0.08243728
